Repository codeit-fe16-part4-team1/project-mogazoa-app, pull requests merged in 2025-09, with the labels that each got.

#137 [Feat] debounce 추가
  package-lock.json
  package.json
  src/components/CompareBar/CompareBar.tsx
Labels: [✨ Feature ], [🔨 Refactor ], 다인

#136 [Feat] 검색 후 무한 스크롤
  src/app/HomeClient.tsx
  src/components/ProductCard/ProductCard.tsx
Labels: [✨ Feature ], 민경

#141 [Feat] z-index 스타일 4종 추가(globals.css)
  src/app/globals.css
Labels: [⚙ Setting ], [🎨 Html&css ], 치영

#147 [Feat] 프로필페이지 - 상품 목록 무한스크롤 적용
  src/app/(user)/components/ProductSection.tsx
  src/app/(user)/mypage/page.tsx
  src/constant/queryKeys.ts
Labels: [✨ Feature ], [🎨 Html&css ], 치영

#148 [Feat] 유저 팔로우/취소 API 제작
  src/api/follow/userFollowAPI.ts
  src/api/follow/userUnFollowAPI.ts
Labels: [✨ Feature ], [📬 API ], 치영

#143 [Feat] 카테고리 필터링 구현
  package-lock.json
  package.json
  src/api/category/getCategories.ts
  src/app/HomeClient.tsx
  src/app/page.tsx
  src/assets/icons/icon_category_app.svg
  src/assets/icons/icon_category_beauty.svg
  src/assets/icons/icon_category_book.svg
  src/assets/icons/icon_category_electronic.svg
  src/assets/icons/icon_category_fashion.svg
  src/assets/icons/icon_category_hotel.svg
  src/assets/icons/icon_category_interior.svg
  src/assets/icons/icon_category_movie.svg
  src/assets/icons/icon_category_music.svg
  src/assets/icons/icon_category_restaurant.svg
  src/components/Category/Category.tsx
  src/components/Category/CategoryButton.tsx
  src/hooks/useCategoryMap.ts
  src/hooks/useHorizontalScroll.ts
Labels: [✨ Feature ], [📬 API ], 민경

#135 [Feat] 상품 상세 페이지 UI 및 일부 기능 구현
  src/api/product/getReviewList.ts
  src/api/review/removeReview.ts
  src/app/globals.css
  src/app/product/[productId]/ProductDetailPage.tsx
  src/app/product/[productId]/components/ProductBtns.tsx
  src/app/product/[productId]/components/ProductDetailHeader.tsx
  src/app/product/[productId]/components/ProductEditButton.tsx
  src/app/product/[productId]/components/ProductImage.tsx
  src/app/product/[productId]/components/ProductInfo.tsx
  src/app/product/[productId]/components/ProductNoReview.tsx
  src/app/product/[productId]/components/ProductReviewCard.tsx
  src/app/product/[productId]/components/ProductReviewList.tsx
  src/app/product/[productId]/components/ProductShareBtns.tsx
  src/app/product/[productId]/components/ProductStatisticCard.tsx
  src/app/product/[productId]/hooks/useProductData.ts
  src/app/product/[productId]/hooks/useProductReviewListData.ts
  src/app/product/[productId]/page.tsx
  src/app/test/(heedong)/likes-test/page.tsx
  src/assets/icons/icon_kakao_share.svg
  src/assets/icons/icon_plus.svg
  src/assets/icons/icon_product_edit.svg
  src/assets/icons/icon_share.svg
  src/assets/img_empty_review.png
  src/components/FloatingButton/FloatingButton.stories.tsx
  src/components/FloatingButton/FloatingButton.tsx
  src/components/Likes/ThumbsUpLikes.stories.tsx
  src/components/Likes/ThumbsUpLikes.tsx
  src/components/Rating/Rating.tsx
  src/constant/queryKeys.ts
  src/types/api.ts
  src/utils/formatDate.ts
Labels: [✨ Feature ], [🎨 Html&css ], 동희

#152 [Feat] 리뷰어 랭킹 구현
  src/api/user/getUserRankingAPI.ts
  src/api/user/getUsersRankingAPI.ts
  src/app/(user)/components/ProductList.tsx
  src/app/HomeClient.tsx
  src/app/components/Category/Category.tsx
  src/app/components/Category/CategoryButton.tsx
  src/app/components/ProductCard/ProductCard.tsx
  src/app/components/UsersRanking/MidRanking.tsx
  src/app/components/UsersRanking/TopRanking.tsx
  src/app/components/UsersRanking/UsersRanking.tsx
  src/app/page.tsx
  src/app/test/userapi/page.tsx
  src/assets/icons/icon_ranking_first.svg
  src/assets/images/noProfile.png
  src/types/api.ts
  tailwind.config.ts
Labels: [✨ Feature ], [📬 API ], 민경

#157 [Feat] useIntersectionObserver 커스텀 훅에 Options 파라미터 추가(옵셔널) 외 커스텀 훅 추가 1건
  config/imageConfig.ts
  next.config.ts
  src/hooks/useIntersectionObserver.ts
  src/hooks/useSafeImageUrl.ts
Labels: [✨ Feature ], 치영

#153 [Feat] 리뷰 생성/편집 다이얼로그 UI 구현
  src/app/test/(heedong)/dialog-test/page.tsx
  src/components/Dialog/ReviewFormDialog.tsx
  src/components/Dialog/core/DialogMap.tsx
  src/types/api.ts
  src/types/dialogProps.types.ts
Labels: [✨ Feature ], [🎨 Html&css ], 동희, point: 4

#164 [Fix] 프로필 페이지 - 프로필 영역 UI 개선
  src/app/(user)/components/ProfileSection/ProfileStats.tsx
  src/app/(user)/components/ProfileSection/components/ProfileImageViewer.tsx
Labels: [🎨 Html&css ], [🥰 Accessibility ], 치영

#160 [Feat] 비교하기 페이지 UI 구현
  src/app/api/products/getProductItemAPI.ts
  src/app/compare/page.tsx
  src/app/globals.css
  src/components/Badge/Badge.tsx
  src/components/CompareBar/CompareBar.tsx
  src/components/CompareCard/CompareCard.tsx
  src/components/CompareDetail/CompareDetail.tsx
  src/components/CompareDetail/CompareDetailDefault.tsx
  src/components/CompareImage/CompareImage.tsx
Labels: [✨ Feature ], [🎨 Html&css ], 다인

#167 [Fix]: ImageInput 컴포넌트 이미지 추가 아이콘 사이즈 수정
  src/components/ImageInput/ImageInput.tsx
Labels: [🎨 Html&css ], 치영

#165 [Feat] 상품 상세 페이지 - 리뷰 추가 및 수정 모달 추가
  src/api/review/createReview.ts
  src/api/review/updateReview.ts
  src/app/product/[productId]/ProductDetailPage.tsx
  src/app/product/[productId]/components/ProductBtns.tsx
  src/app/product/[productId]/components/ProductReviewCard.tsx
  src/app/product/[productId]/components/ProductReviewList.tsx
  src/components/Dialog/ReviewFormDialog.tsx
  src/components/FloatingButton/FloatingButton.tsx
  src/components/TextArea/TextArea.tsx
  src/types/dialogProps.types.ts
Labels: [✨ Feature ], 동희, point: 10

#178 [Refactor] Dropdown 줄바뀜 수정
  src/components/Dropdown/Dropdown.tsx
Labels: [🔨 Refactor ], 다인

#181 [Feat] 리스트 로딩용 인디케이터 추가
  src/components/ThreeDotIndicator/ThreeDotIndicator.stories.tsx
  src/components/ThreeDotIndicator/ThreeDotIndicator.tsx
Labels: [✨ Feature ], [🎨 Html&css ], 동희

#171 [Feat] 로딩, not-found 페이지
  src/app/layout.tsx
  src/app/loading/loading.tsx
  src/app/not-found.tsx
Labels: [✨ Feature ], 민경

#182 [Refactor] 프로필 페이지 수정
  src/app/(user)/components/ProductSection.tsx
  src/app/(user)/components/ProductSection/ProductList.tsx
  src/app/(user)/components/ProductSection/ProductOptionList.tsx
  src/app/(user)/components/ProfileSection.tsx
  src/app/(user)/layout.tsx
  src/app/(user)/mypage/page.tsx
  src/app/(user)/user/[userId]/page.tsx
  src/lib/baseAPI.ts
  src/utils/cookieOptions.ts
Labels: [📬 API ], [🔨 Refactor ], 치영

#174 [Feat] 상품 추가 및 수정 다이얼로그 추가
  src/api/product/createProduct.ts
  src/api/product/updateProduct.ts
  src/app/product/[productId]/ProductDetailPage.tsx
  src/app/product/[productId]/components/ProductEditButton.tsx
  src/app/product/[productId]/components/ProductReviewCard.tsx
  src/app/product/[productId]/components/ProductReviewList.tsx
  src/app/product/[productId]/page.tsx
  src/app/test/(heedong)/dialog-test/page.tsx
  src/components/Dialog/ProductFormDialog.tsx
  src/components/Dialog/core/DialogMap.tsx
  src/components/ImageInput/ImageInput.tsx
  src/types/dialogProps.types.ts
Labels: [✨ Feature ], 동희, point: 14

#197 [Feat] 401 에러 시 /signin Redirect 로직 구현
  package-lock.json
  package.json
  src/app/(auth)/signin/page.tsx
  src/app/(user)/components/ProfileSection/ProfileStats.tsx
  src/app/(user)/mypage/page.tsx
  src/app/(user)/user/[userId]/page.tsx
  src/app/components/ProductCard/ProductCard.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/assets/icons/icon_toast_fail.svg
  src/assets/icons/icon_toast_info.svg
  src/assets/icons/icon_toast_success.svg
  src/components/Toast/Toast.tsx
  src/lib/baseAPI.ts
Labels: [📬 API ], [🥰 Accessibility ], 치영

#198 [Fix] ImageInput 컴포넌트 - required 속성 추가(이미지 없어도 폼 제출 가능하도록 수정)
  src/components/ImageInput/ImageInput.stories.tsx
  src/components/ImageInput/ImageInput.tsx
Labels: [✨ Feature ], [🐞 BugFix ], 치영

#205 [Refactor] FormField 컴포넌트 애니메이션 추가/회원가입,로그인 UI 조정
  src/app/(auth)/components/AuthSection.tsx
  src/app/(auth)/components/KakaoButton.tsx
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/globals.css
  src/components/FormField/FormField.tsx
Labels: [🎨 Html&css ], [🔨 Refactor ], 치영

#212 [Feat] 인증 상태가 아닐 시, 버튼 비활성화 및 버튼 사이즈 재조정
  src/app/product/[productId]/ProductDetailPage.tsx
  src/app/product/[productId]/components/ProductBtns.tsx
  src/app/product/[productId]/components/ProductReviewCard.tsx
  src/app/product/[productId]/components/ProductReviewList.tsx
  src/app/product/[productId]/components/ProductShareBtns.tsx
  src/app/product/[productId]/page.tsx
  src/components/Likes/HeartLikes.stories.tsx
  src/components/Likes/HeartLikes.tsx
  src/components/Likes/ThumbsUpLikes.stories.tsx
  src/components/Likes/ThumbsUpLikes.tsx
Labels: [✨ Feature ], [🎨 Html&css ], 동희, point: 2

#172 [Refactor] 메인 페이지 쿼리 구조 수정
  src/app/HomeClient.tsx
  src/app/components/Category/Category.tsx
  src/components/Header/Header.tsx
  src/components/Header/SearchInput.tsx
Labels: [🔨 Refactor ], 민경

#200 [Feat] 상품 전역 상태 + localStorage 관리
  package-lock.json
  package.json
  src/app/compare/page.tsx
  src/app/dropdowntest/page.tsx
  src/components/Dialog/CompareConfirmDialog.tsx
  src/store/useCompareStore.ts
Labels: [✨ Feature ], 다인

#213 [refactor] 간편 로그인/회원가입 로직 리팩토링
  src/app/(auth)/components/AuthSection.tsx
  src/app/(auth)/layout.tsx
  src/app/(auth)/oauth/signin/kakao/callback/page.tsx
  src/app/(auth)/oauth/signup/kakao/SignupKakao.tsx
  src/app/(auth)/oauth/signup/kakao/callback/page.tsx
  src/app/(auth)/oauth/signup/kakao/page.tsx
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/page.tsx
  src/lib/redirectKakaoAuth.ts
Labels: [✨ Feature ], [🎨 Html&css ], [🔨 Refactor ], 치영

#219 [Fix]: 리뷰 삭제 버튼 클릭 시, 확인 메세지를 받도록 수정
  src/app/product/[productId]/components/ProductReviewCard.tsx
Labels: [🐞 BugFix ], 동희

#269 [Fix] ProductCard 디자인 수정
  src/app/(auth)/components/AuthLinks.tsx
  src/app/components/ProductCard/ProductCard.tsx
Labels: [🎨 Html&css ], 치영

#264 [Fix] 다이얼로그 닫기 제어(ESC, 외부 클릭)가 isClosing에 의해 제어되지 않아 라우팅이 여러번 실행되던 문제 수정
  src/components/Dialog/core/DialogComponents.tsx
  src/hooks/useDialog.ts
Labels: [🎨 Html&css ], [🐞 BugFix ], 동희, point: 1

#270 [Fix] 아이콘 흰색 배경 제거, 디자인 수정
  src/assets/icons/icon_compare_default.svg
  src/assets/icons/icon_home_default.svg
  src/assets/icons/icon_my_default.svg
  src/assets/icons/icon_toast_success.svg
Labels: [🎨 Html&css ], 치영

#267 [Refactor] 상품 입력창 데이터 패칭 방법 변경
  src/app/compare/CompareContent.tsx
  src/app/compare/page.tsx
  src/components/CompareBar/CompareBar.tsx
  src/components/CompareCard/CompareCard.tsx
Labels: [ 🛠️ Suggestion], [🔨 Refactor ], 다인

#262 [Refactor] 중간점검 보완
  package-lock.json
  package.json
  src/app/HomeClient.tsx
  src/app/components/ProductList/BestProducts.tsx
  src/app/components/ProductList/FilteredProducts.tsx
  src/app/components/ProductList/HighRatingProducts.tsx
  src/app/globals.css
  src/assets/icons/logo_mobile.svg
  src/components/Header/Header.tsx
  src/components/Header/SearchInput.tsx
Labels: [🔨 Refactor ], 민경

#272 [Feat] OpenGraph 이미지 제작
  .gitignore
  public/images/image_opengraph_wide_mogazoa.png
  src/app/compare/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
Labels: [🌏 Deploy ], 치영

#274 [Refactor] axios 응답 인터셉터에 404 에러 시 notFound Redirect 구문 추가
  src/app/(user)/user/[userId]/page.tsx
  src/lib/baseAPI.ts
Labels: [📬 API ], [🔨 Refactor ], 치영

#277 [Feat] sitemap 생성
  src/app/sitemap.ts
Labels: [🥰 Accessibility ], 치영

#279 [Fix] 접근성, 검색엔진 최적화 점수 확보
  src/app/(auth)/components/KakaoButton.tsx
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(user)/components/ProfileSection/components/ProfileImageInput.tsx
  src/app/compare/page.tsx
  src/app/components/ProductList/HighRatingProducts.tsx
  src/app/page.tsx
  src/app/product/[productId]/components/ProductReviewCard.tsx
  src/components/CompareBar/CompareBar.tsx
  src/components/Header/SearchInput.tsx
  src/components/ImageInput/ImageInput.tsx
  src/components/Likes/HeartLikes.tsx
  src/components/Likes/ThumbsUpLikes.tsx
  src/components/OptionList/OptionList.tsx
  src/components/Rating/Rating.tsx
Labels: [🌏 Deploy ], [🔨 Refactor ], [🥰 Accessibility ], 치영

#281 [Fix] 메인페이지 배너 - 반복이미지 패턴 LCP 개선을 위한 preload 적용
  src/app/layout.tsx
Labels: [🥰 Accessibility ], 치영

#282 [Fix] 메인페이지 - 리뷰어 랭킹 이미지 sizes 최적화
  src/app/components/UsersRanking/TopRanking.tsx
Labels: [🥰 Accessibility ], 치영

#285 [Fix] 메인페이지 - 페이지네이션 번호 접근성 점수 개선을 위한 색상 수정
  src/app/components/ProductList/HighRatingProducts.tsx
Labels: [🥰 Accessibility ], 치영

#294 [Refactor] 프로필 페이지 리팩토링
  src/api/user/getUserProductsAPI.ts
  src/api/user/getUserProfileAPI.ts
  src/app/(user)/ProfilePage.tsx
  src/app/(user)/components/ProductSection.tsx
  src/app/(user)/components/ProductSection/ProductList.tsx
  src/app/(user)/components/ProductSection/ProductOptionList.tsx
  src/app/(user)/components/ProfileSection/ProfileStats.tsx
  src/app/(user)/mypage/page.tsx
  src/app/(user)/user/[userId]/page.tsx
  src/app/components/ProductCard/ProductCard.tsx
  src/components/Chip/CategoryChip.tsx
  src/components/OptionList/OptionList.tsx
  src/lib/categoryList.ts
  src/lib/metadata/profile.ts
Labels: [🔨 Refactor ], 치영

#295 [Fix] OpenGraph Image 변경
  public/images/image_opengraph_wide_mogazoa.png
Labels: [🌏 Deploy ], [🥰 Accessibility ], 치영
