Repository codeit-fe16-part4-team1/project-mogazoa-app, pull requests merged in 2025-08, with the labels that each got.

#20 [Feat] Storybook PR Preview 기능 제작
  .github/workflows/deploy.yml
  .github/workflows/pr-preview-cleanup.yml
  .github/workflows/pr-preview-deploy.yml
  .github/workflows/pr-preview-storybook-deploy.yml
  .github/workflows/storybook-deploy.yml
  src/components/Button/Button.stories.tsx
Labels: [⚙ Setting ], [✅ Test ], [🌏 Deploy ], 치영

#96 @storybook/addon-onboarding 삭제
  .storybook/main.ts
Labels: [✅ Test ], [🔨 Refactor ], 다인

#97 [Feat] 헤더 UI 구현
  public/logo.svg
  public/menu.svg
  public/search.svg
  src/app/globals.css
  src/app/layout.tsx
  src/components/Header/Header.tsx
Labels: [✨ Feature ], [🎨 Html&css ], 민경

#98 [Feat] 디자인 시스템 - CategorieChip 구현
  package-lock.json
  package.json
  src/components/Chip/CategorieChip.stories.tsx
  src/components/Chip/CategorieChip.tsx
  src/utils/generateColorsFromText .ts
Labels: [ 🛠️ Suggestion], [✅ Test ], [✨ Feature ], [🎨 Html&css ], 동희

#95 [Feat] Kakao JS SDK Init 구문 추가, Kakao SDK 관련 Type 추가
  .github/workflows/deploy.yml
  .github/workflows/pr-preview-deploy.yml
  src/app/Providers.tsx
  src/app/layout.tsx
  src/hooks/useKakaoInitialize.tsx
  src/types/global.d.ts
  src/types/kakao.d.ts
Labels: [✨ Feature ], [📬 API ], 치영

#104 [Feat] prettier-plugin-tailwindcss 설치 및 적용
  .prettierrc
  .vscode/settings.json
  package-lock.json
  package.json
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/page.tsx
  src/app/test/userapi/page.tsx
  src/components/FormField/FormHint.tsx
  src/components/FormField/FormInput.tsx
  src/components/Header/Header.tsx
  src/stories/ColorPalette.stories.tsx
  src/stories/Typography.stories.tsx
Labels: [⚙ Setting ], [🎨 Html&css ], 치영

#103 [Feat] 공용 컴포넌트 Button 제작
  src/components/Button/Button.stories.tsx
  src/components/Button/Button.tsx
Labels: [✅ Test ], [✨ Feature ], [🎨 Html&css ], 다인

#105 [Feat] 회원가입/로그인 페이지용 FormField 컴포넌트 제작
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/oauth/signup/kakao/page.tsx
  src/assets/icons/icon_formfield_email.svg
  src/assets/icons/icon_formfield_nickname.svg
  src/assets/icons/icon_formfield_password.svg
  src/assets/icons/icon_password_invisible.svg
  src/assets/icons/icon_password_visible.svg
  src/components/FormField/FormField.tsx
  src/components/FormField/FormHint.tsx
  src/components/FormField/FormInput.tsx
  src/components/FormField/FormLabel.tsx
Labels: [✨ Feature ], [🎨 Html&css ], 치영

#112 [Feat] 공용컴포넌트 ImageInput 제작
  .storybook/main.ts
  package-lock.json
  package.json
  src/api/image/getUploadedImageUrlAPI.ts
  src/app/test/imageinput/page.tsx
  src/assets/icons/icon_imageinput_add.svg
  src/assets/icons/icon_imageinput_delete.svg
  src/components/ImageInput/ImageInput.stories.tsx
  src/components/ImageInput/ImageInput.tsx
Labels: [✨ Feature ], [🎨 Html&css ], 치영

#121 [Refactor] svg 원복
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/DropdownIcon.tsx
Labels: [🔨 Refactor ], 다인

#114 [Feat] 메인 페이지 초기 상품 목록 구현
  next.config.ts
  src/api/products/getProductsAPI.ts
  src/app/HomeClient.tsx
  src/app/page.tsx
  src/components/Header/Header.tsx
  src/components/PaginationButton/PaginationButton.tsx
  src/components/ProductCard/ProductCard.tsx
  src/hooks/useIsDesktop.ts
  src/store/useFilterStore.ts
Labels: [✨ Feature ], [📬 API ], 민경

#110 [Feat] 공용 컴포넌트 다이얼로그 추가
  .vscode/settings.json
  package-lock.json
  package.json
  src/app/globals.css
  src/app/layout.tsx
  src/components/Dialog/TestDialog.tsx
  src/components/Dialog/TestInnerDialog.tsx
  src/components/Dialog/core/DialogComponents.tsx
  src/components/Dialog/core/DialogMap.tsx
  src/components/Dialog/core/GlobalDialog.tsx
  src/hooks/useDialog.ts
  src/store/useDialogStore.ts
  src/types/dialog.types.ts
  src/types/dialogProps.types.ts
Labels: [✨ Feature ], point: 12

#117 [Fix] font의 lineHeight값 Figma와 브라우저간 차이로 인해 Figma 디자인 시스템 기준 고정값 설정
  tailwind.config.ts
Labels: [🎨 Html&css ], 치영

#116 [Feat] 하트 및 엄지척 좋아요 컴포넌트 추가
  src/assets/icons/icon_heart.svg
  src/assets/icons/icon_thumbs_up.svg
  src/components/Likes/HeartLikes.stories.tsx
  src/components/Likes/HeartLikes.tsx
  src/components/Likes/ThumbsUpLikes.stories.tsx
  src/components/Likes/ThumbsUpLikes.tsx
  tailwind.config.ts
Labels: [✨ Feature ], [🎨 Html&css ], 동희, point: 4

#125 [Fix] Preview Deploy 구문 수정
  .github/workflows/pr-preview-deploy.yml
Labels: [✨ Feature ], [🌏 Deploy ], 치영

#123 [Feat] 간편 회원가입/로그인 에러처리 적용, 에러 페이지 적용, flow 수정
  public/images/image_error.png
  src/app/(auth)/components/AuthSection.tsx
  src/app/(auth)/components/FormFieldContainer.tsx
  src/app/(auth)/components/KakaoButton.tsx
  src/app/(auth)/oauth/signin/kakao/callback/page.tsx
  src/app/(auth)/oauth/signup/kakao/callback/page.tsx
  src/app/(auth)/oauth/signup/kakao/page.tsx
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/error/page.tsx
  src/app/globals.css
  src/lib/redirectKakaoAuth.ts
Labels: [✨ Feature ], [🎨 Html&css ], 치영

#127 [Feat] 검색 기능 구현
  package-lock.json
  package.json
  src/app/HomeClient.tsx
  src/app/layout.tsx
  src/app/not-found.tsx
  src/components/Header/Header.tsx
  src/components/ProductCard/ProductCard.tsx
  src/components/Sort/Sort.tsx
Labels: [✨ Feature ], [📬 API ], 민경

#124 [Feat] 상품입력창 구현
  src/app/api/products/getProductItemAPI.ts
  src/app/comparetest/page.tsx
  src/assets/icons/IconClose.svg
  src/components/CompareBar/CompareBar.tsx
  src/components/Dialog/core/DialogComponents.tsx
Labels: [✨ Feature ], 다인
